#!/bin/sh
### BEGIN INIT INFO
# Provides:          pstarter
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop node servers batch script
### END INIT INFO
NODE_BIN=/home/pstarter/bin
SERVER="pstarter.js"

PID_FILE="/var/run/pstarter.pid"
NODEJS=/usr/bin/nodejs
NODE_ENV=production

cleanup_pid() {
        cat > $PID_FILE &
        echo "clean up"
}

stop_server() {
	echo "Stop node server"
	PID=$(cat $PID_FILE)
	kill $PID > /dev/null 2&>1&
	#while [ "$PID" != "" ]; do
	#	sleep 0.1
	#	PID=$(cat $PID_FILE)
	#done
	echo "Node server stopped!"
}

start_server() {
	echo "Start node server"
    cleanup_pid
    cd $NODE_BIN
    $NODEJS $SERVER NODE_ENV=$NODE_ENV PID_FILE=$PID_FILE > /dev/null 2&>1&
    echo "Node server started"
}

gracefull_server() {
	echo "Graceful node server"
	PID=$(cat $PID_FILE)
	kill -s USR2 $PID
	echo "Graceful node server done"
}

restart_server() {
	echo "Restart node server"
	PID=$(cat $PID_FILE)
	kill -s HUP $PID
	echo "Restart node server done"
}

case "$1" in
	force-restart)
		stop_server
		sleep 1
		start_server
		exit 0
		;;
	graceful)
		gracefull_server
		exit 0
		;;
        start)
            start_server
            exit 0
             ;;
        stop)
        	stop_server
            exit 0
             ;;
        restart)
        	restart_server
        	exit 0
esac

